name: CI Commitlint

on:
  push:
    branches: ['**']
  pull_request:
    branches: [core]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install commitlint
        run: npm install --no-save @commitlint/cli @commitlint/config-conventional

      - name: Validate push commit
        if: github.event_name == 'push'
        run: >
          npx commitlint
          --from ${{ github.event.before }}
          --to ${{ github.event.after }}

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: >
          npx commitlint
          --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }}
